version: 0.2

phases:
  install:
    commands:
      - cd clothing‑store
      - npm install
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  base-directory: build  # Directory with output files (e.g, React app)
